### ISSUE TITLE
能否再出个js 版本 

### ISSUE THREAD

**Issue by Yunnathai** [wcly/react-native-better-template#1]

**Comment by wcly** [comment]
目前没这个打算
- 你可以参考我的文章自己创建一个js的模板：[手把手教你创建一个自定义react-native项目模板](https://juejin.cn/post/6925317074277531655)
- 也可以直接用当前模板，ts是js的超集，项目配置了ts不影响你直接使用js写代码，等你哪天想换ts也不需要重新配置了
